### ISSUE TITLE
A series of articles focused on the nuances of the estimation process, broken link

### ISSUE THREAD

**Issue by miketabb33** [pragmint/open-practices#1]
The following link from our best practices repo seems to take me to a site where articles don’t open. Is this the same for you?
[A series of articles focused on the nuances of the estimation process](https://practisingxp.com/tag/estimation/)
Its located here in our best practices repo: https://github.com/pragmint/best-practices/blob/main/teamwork/clarity.md

**Comment by dcmoore** [comment]
We restructured the repo and this is no longer an issue. Thanks for reporting!
