### ISSUE TITLE
Need permission to view vimeo video

### ISSUE THREAD

**Issue by miketabb33** [pragmint/open-practices#2]
The resource is located [here](https://github.com/pragmint/best-practices/blob/main/adaptability/reuse.md)
and is
[Sandi Metz's talk on SOLID OOO](https://vimeo.com/12350535)

<img width="1440" alt="Screen Shot 2022-07-28 at 10 07 37 AM" src="https://user-images.githubusercontent.com/36526318/181526031-775aa882-3e56-4017-b83f-e4e345de09ec.png">

**Comment by dcmoore** [comment]
No longer listing this broken link
